ARG version
FROM almalinux:${version:-8}
# RUN cat /etc/*release
ARG COURSE=Docker
ARG TRAINER=Siva
ARG Duration=120hrs
ENV Duration=120hrs
RUN echo "Course is : ${COURSE}, Trainer is : ${TRAINER}, Duration is ${Duration}"
CMD ["sleep","200"]